# -*- coding: utf-8 -*-
"""Robotika.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jf-jo4za5ZuG9c2z9BgdJ7C1d0npJmYF
"""

x = 42
y = 3.14
tekst = "Hello"
print(x, type(x))
print(y, type(y))
print(tekst, type(tekst))

a = 10
b = 7
print("Zbroj:", a+b)
print("Umnožak", a*b)

if a>b:
  print("A je veće od B")
elif a<b:
  print("A je manje od B")
else:
  print("A je jednako B")
print("Kraj neovisan o ifovima")

brojevi = [1,2,3,4,5]
for i in brojevi:
  print(i)

def kvadrat(n):
  return n**2

print(kvadrat(5))

for n in range(2, 99, 7):
  print(n)

lista = [1,2,3]
dictionary = {"ime": "Pero", "prezime": "Perić"}

with open("tekst.txt", "w") as f:
  f.write("Ovo je prvi red\n")

with open("tekst.txt", "r") as f:
  print(f.read())

import numpy as np
a = np.array([1,2,3,4,5])
print("Array: ", a)
print("Tip: ", type(a))

print("zbroj", np.sum(a))
print("srednja vrijednost", np.mean(a))
print("st. dev", np.std(a))

M = np.array([[1,2], [3,4]])
N = np.array([[5,6], [7,8]])

print("Matrica:\n", M)
print("Transponirano M;\n", M.T)
print("MxN:\n", np.dot(M,N))

np.random.seed(0)
slucajni = np.random.rand(5)
print(slucajni)

X = np.arange(6).reshape(2,3)
print(X)
v = np.array([1,2,3])
print("X+v: ", X + v)

# kad govorimo o 2d shapeu, gre: retci/stupci

import sympy as sp

x, y, z = sp.symbols('x y z')
a, b = sp.symbols('a b', real=True)

f = sp.sin(x) * sp.exp(x**2)
df_dx = sp.diff(f, x)
print(df_dx)
d2f_dx2 = sp.diff(f, x, 2)
print(d2f_dx2)
g = x**2 * y + sp.sin(y)
dg_dx = sp.diff(g, x)
dg_dy = sp.diff(g, y)
print(dg_dx)
print(dg_dy)
int_f = sp.integrate(f, x)
print(int_f)
int_f_bounds = sp.integrate(f, (x, 0, 1))
print(int_f_bounds)
h = x*y
double_int = sp.integrate(h, (x, 0, 1), (y, 0, 2))
print(double_int)